Gradient Circle
skywinder/GaugeKit pull request #35
Opened 2016-05-18 14:23 UTC by sinanulkuatam

![gradient](https://cloud.githubusercontent.com/assets/1269987/15362231/93c92d16-1ce2-11e6-9f7c-523b5eadf9f2.gif)

2016-05-18 15:05 UTC, sinanulkuatam commented
@skywinder It looks like it's complaining about these two lines

`super.init(coder: aDecoder)` and `gaugeLayer = getGauge(rotateAngle: rotate / 10 * M_PI)`

which I changed to 

`super.init(coder: aDecoder)!` and `gaugeLayer = getGauge(rotate / 10 * M_PI)`

Current project won't compile without the changes I made to run locally, thoughts?

2016-05-19 11:27 UTC, skywinder commented
@sinanulkuatam please wait for merge of #32,  I hope it will not make merge conflicts. It should remove some problems and will update syntax a bit

2016-05-19 12:09 UTC, sinanulkuatam commented
@skywinder yes you're right about adding it as an internal framework, I'll make that change today

2016-05-19 12:56 UTC, sinanulkuatam commented
@skywinder a couple changes, I removed the Pods and all dependencies around the build for it.  I had a couple issues embedding it directly as it pointed to my own derived data, so instead of running Example.xcodeproj you can run GaugeKit.xcworkspace and change your scheme to run the example.  I will update the readme to take this into account.

2016-05-21 22:55 UTC, sinanulkuatam commented
@skywinder let me know if there are any issues with the branch/PR

2016-05-30 11:20 UTC, skywinder commented on Example/Example/Base.lproj/Main.storyboard
> +                                    <view contentMode="scaleToFill" misplaced="YES" translatesAutoresizingMaskIntoConstraints="NO" id="q6f-rg-MaX" userLabel="GaugeMid" customClass="Gauge" customModul
Can you kindly mix misplaced views?

2016-05-30 11:21 UTC, skywinder commented
There is also broken test in this build: https://travis-ci.org/skywinder/GaugeKit/builds/131408468#L310

2016-05-30 11:29 UTC, skywinder commented on GaugeKit/Gauge.swift
> +    @IBInspectable public var bottomGradientColor: UIColor = UIColor.redColor() {
Are you sure, that we have to add 2 additional properties? Why you don't use `startColor` and `endColor` properties in `Gauge.swift`? they are useless in circle yet. I think too many properties can confuse users.

2016-05-30 11:56 UTC, sinanulkuatam commented on Example/Example/Base.lproj/Main.storyboard
> +                                    <view contentMode="scaleToFill" misplaced="YES" translatesAutoresizingMaskIntoConstraints="NO" id="q6f-rg-MaX" userLabel="GaugeMid" customClass="Gauge" customModul
Not sure why they are now misplaced, didn't change the storyboard and the demo project runs across all device sizes.  Will check what the issue is however

2016-05-30 11:57 UTC, sinanulkuatam commented on GaugeKit/Gauge.swift
> +    @IBInspectable public var bottomGradientColor: UIColor = UIColor.redColor() {
I agree, removed

2016-10-04 08:52 UTC, skywinder requested changes
Hi. Sorry for late reply. As I can see you make a good addition to the project. But sadly it's updated to swift 3.0. I would like to review your PR if you  can update it to current status of the project/

2016-10-04 08:52 UTC, skywinder commented on .gitignore
> -# Pods/
Please, don't add it to gitignore

2016-10-04 08:52 UTC, skywinder commented on README.md
> +Open `GaugeKit.xcworkspace` and change the scheme to 'Example' and run Example project.
That's good addition

2016-10-04 08:53 UTC, skywinder approved these changes

2016-10-04 09:03 UTC, skywinder commented
Thank you for PR. 
And sorry for late reply.
The project is moved to Swift 3. I would like to review your changes if you will able to synchronize it with current version.

2016-10-04 13:01 UTC, sinanku commented
I will have time later this week to work on it, thanks for the update!

2017-11-21 23:31 UTC, skywinder commented
I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍
Please let me know, you going to update it to up-to date version and fix minor things!

2017-11-26 22:56 UTC, sinanku commented
@skywinder I'll be able to take a look in a few weeks, wrapping up grad school at the moment!

2019-12-26 10:01 UTC, skywinder commented
CLosed in favor of #68

2019-12-26 10:01 UTC, closed without merging